In [168]:
import numpy as np

In [169]:
matrix_1 = np.array([1,1,3,0,5,0,7,0,9,0,11,0,13,0,15,1]).reshape(4,4)

In [150]:
matrix_1

array([[ 1,  1,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  1]])

In [151]:
def set_pivot(matrix, row):
    ret_matrix = matrix.copy()
    target_row = ret_matrix[row,:]
    divide_by = target_row[row]
    
    ret_matrix[row,:] = target_row / divide_by
    
    print(ret_matrix)
    
    return ret_matrix

In [152]:
def add_row(matrix, target_index, adding_index, scaler):
    ret_matrix = matrix.copy()
    target_row = ret_matrix[target_index,:]
    adding_row = ret_matrix[adding_index,:]
    resultant_row = target_row + adding_row*scaler
    ret_matrix[target_index,:] = resultant_row
    
    print(ret_matrix)
    
    return ret_matrix

In [153]:
def swap_rows(matrix, row1_index, row2_index):
    ret_matrix = matrix.copy()
    
    ret_matrix[row1_index,:] = matrix[row2_index,:]
    ret_matrix[row2_index,:] = matrix[row1_index,:]
    
    return ret_matrix

In [154]:
matrix_1

array([[ 1,  1,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  1]])

In [155]:
matrix_1 = set_pivot(matrix_1, 0)

[[ 1  1  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  1]]


In [156]:
matrix_1 = add_row(matrix_1,1,0,-5)

[[ 1  1  3  0]
 [ 0 -5 -8  0]
 [ 9  0 11  0]
 [13  0 15  1]]


In [157]:
matrix_1 = add_row(matrix_1,2,0,-9)

[[  1   1   3   0]
 [  0  -5  -8   0]
 [  0  -9 -16   0]
 [ 13   0  15   1]]


In [158]:
matrix_1 = add_row(matrix_1,3,0,-13)

[[  1   1   3   0]
 [  0  -5  -8   0]
 [  0  -9 -16   0]
 [  0 -13 -24   1]]


In [159]:
matrix_1 = set_pivot(matrix_1, 1)

[[  1   1   3   0]
 [  0   1   1   0]
 [  0  -9 -16   0]
 [  0 -13 -24   1]]


In [160]:
matrix_1 = add_row(matrix_1, 0,1,-1)

[[  1   0   2   0]
 [  0   1   1   0]
 [  0  -9 -16   0]
 [  0 -13 -24   1]]


In [161]:
matrix_1 = add_row(matrix_1, 2,1,9)

[[  1   0   2   0]
 [  0   1   1   0]
 [  0   0  -7   0]
 [  0 -13 -24   1]]


In [162]:
matrix_1 = add_row(matrix_1, 3,1,13)

[[  1   0   2   0]
 [  0   1   1   0]
 [  0   0  -7   0]
 [  0   0 -11   1]]


In [163]:
matrix_1 = set_pivot(matrix_1, 2)

[[  1   0   2   0]
 [  0   1   1   0]
 [  0   0   1   0]
 [  0   0 -11   1]]


In [164]:
matrix_1 = add_row(matrix_1, 0,2,-2)

[[  1   0   0   0]
 [  0   1   1   0]
 [  0   0   1   0]
 [  0   0 -11   1]]


In [165]:
matrix_1 = add_row(matrix_1, 1,2,-1)

[[  1   0   0   0]
 [  0   1   0   0]
 [  0   0   1   0]
 [  0   0 -11   1]]


In [166]:
matrix_1 = add_row(matrix_1, 3,2,11)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Automte the above for any matrix

1. given a matrix
2. get the number of rows and columns
3. starting with the first row, apply set_pivot
4. for each other row, take take the value of the first item and apply add_row() function to cancel it.
5. Move to the next row, apply set_pivot
6. for each other row....


Continue until complete.

Need to check for a few things:
1. before using set_pivot, need to check if the current value is 0.
2. if current value is zero, need to swap current row with another row that has value at this index
3. if there are no rows with a value at this index, shift column index +1 while keeping on same row. Repeat above steps

In [177]:
def can_pivot(col):
    if col[0] != 0:
        return True
    else:
        return False

In [178]:
def determine_add_scaler(matrix, target_row_index, pivot_col):
    target_row = matrix[target_row_index,:]
    
    value = target_row[pivot_col]
    
    return -value
    
    

In [172]:
matrix_1

array([[ 1,  1,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  1]])

In [171]:
rows = matrix_1.shape[0]
columns = matrix_1.shape[1]

In [173]:
pivot_row = 0
pivot_col = 0



In [174]:
first_column = matrix_1[:,0]

In [176]:
first_column[0]

1

In [179]:
matrix_1

array([[ 1,  1,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  1]])

In [ ]:
pivot = 0
for i in range(rows):
    first_pivot_value = matrix_1[i,:][pivot]
    if first_pivot_value == 0